package com.bravvura.nestledtime.utils;

/**
 * Created by Deepak Saini on 08-02-2018.
 */

public enum FRAGMENTS {
    LOCAL_ALBUM, LOCAL_PHOTO, LOCAL_ALBUM_PHOTO,
    FACEBOOK_ALBUM, FACEBOOK_PHOTO, FACEBOOK_ALBUM_PHOTO,
    INSTAGRAM_ALBUM, INSTAGRAM_PHOTO, INSTAGRAM_ALBUM_PHOTO,
    AUDIO_RECORDER
}
